# Generated by Django 5.2.8 on 2025-11-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(choices=[('INDIA', 'India'), ('AMERICA', 'America')], default='INDIA', max_length=10),
        ),
    ]
